[project]
name = "neurotech-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diskcache>=5.6.3",
    "fal-client>=0.13.1",
    "gpype>=3.0.9",
    "httpx>=0.28.1",
    "opencv-python-headless>=4.10.0",
    "pillow>=11.0.0",
]
